### ISSUE TITLE
Research QR code generator

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/service-qr-code-generator#1]
Look for candidates with the following properties:

1. Has an Apache 2.0 or MIT license 
2. Ideally written in Golang, or Python
3. Optionally is containerized
4. Optionally has a web server with API to generate QR code images
5. Optionally with image/icon in the center

**Comment by julianchen215** [comment]
@joewxboy May you please assign this issue to me?

**Comment by joewxboy** [comment]
@julianchen215 could you please talk to Mahi and see what work she may have already done?
