### ISSUE TITLE
Add MAINTAINERS.md file

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/service-qr-code-generator#2]
Please duplicate the file in https://raw.githubusercontent.com/open-horizon-services/web-helloworld-cpp/ac403917069c896f685a317f4ca6b503694f5187/MAINTAINERS.md in this repo.

**Comment by helloshiv01** [comment]
please assign me this issue

**Comment by joewxboy** [comment]
Sure thing, @helloshiv01 .  Don't forget to sign-off on your commits.

**Comment by joewxboy** [comment]
Completed
