### ISSUE TITLE
Add lightweight web server in front

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/service-qr-code-generator#6]
Since the library is essentially a CLI, we need to add a web server in front of this to expose the options to a URL.  Let's work through the details and outline which parameters we want to expose, valid value ranges, and what a URL request would look like, along with responses including error conditions.

**Comment by joewxboy** [comment]
Starting with[ the example](https://github.com/joewxboy/web-helloworld-python/blob/main/web-hello.py) in `web-helloworld-python`, create a web server using Flask.  The example code responds to all IP addresses (0.0.0.0) and listens on a particular port (8000).  Later, we can make those configurable in the Makefile, but leave them hardcoded for now.

Notice that the example creates a response in text stored in a variable named `template`.  It then creates a route and prints out the template when it receives a request that responds to the route.  For example, opening the following URL creates the GET request that corresponds to the configuration in the file:

`http://<ip address here, ex. 127.0.0.1 if running locally>:8000/`

The protocol is "http", the IP address is local or the IP of the machine running the python code, the port is 8000 and the path is /

# Step One
What you will want to do first is make the request call the QR code generator library (hard code the values for now), and take the resulting image and return it instead of the template variable.  See if you can capture the QR code image in memory rather than writing to a file and then reading the file.  This will allow us to respond to more than one request without returning the wrong image.  The default [HTTP response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) (not in the code) is Content-type: text/html  You'll need to change that to something like image/jpeg

# Step Two (for Mahi)
NOTE: assuming a URL like: `http://hzncli.local/image?ip=127.0.0.1`
Configure QR code with query parameters in the request.  Add an optional query parameter named `ip`.  If the query param is present and contains an IP address, then assign the value to a global variable.

**Comment by WilliamLi10** [comment]
Hey @joewxboy can I please get assigned this?

**Comment by joewxboy** [comment]
You got it, @WilliamLi10

**Comment by mahi-pas** [comment]
@joewxboy can you add me?
